[streamer]
# Where to find files to stream
StorageDir = "../queue/"

# Port for streaming
StreamPort = 8000

# Output directory for m3u file to configure streaming clients
m3uDirectory = "../"

[converter]
# Accepted File Types, comma separated
AcceptedFileTypes = [ 
					".ogg",
					".flac",
					".wav",
					".aac"
					]

# Bitrate of channel, in kbps
Bitrate = 256

# Where the files uploaded by users will be stored
UploadDirectory = "../uploads/"

# Where the files converted will be stored
StreamDirectory = "../queue/"

[dashboard]
# How long to keep metadata records in database after they've been played, in seconds
MetadataRetentionSec = 86400